<?php $helper = Mage::helper('linkwise'); ?>
<?php if ($helper->isEnabled()): ?>

    <script>
        lw("setCurrency", "978"); // 978 for €
        <?php echo $this->dataToJS();?>
    </script>
    <noscript>
        <img
            src="//go.linkwi.se/delivery/acl.php?program=<?php echo $helper->getLinkwiseId(); ?>&amp;decimal=<?php echo $helper->getDecimalSeparator(); ?>&amp;<?php echo $this->dataToURL(); ?>"
            style="width:0px;height:0px;"/>
    </noscript>

<?php endif; ?>

<?php // Zend_Debug::dump($this->getSuccessData()); ?>
